package quickhttp

var (
	bytesCRLF               = []byte("\r\n")
	bytesHTTP11             = []byte("HTTP/1.1")
	bytesColonSpace         = []byte(": ")
	bytesServer             = []byte(HeaderServer)
	bytesExpect             = []byte(HeaderExpect)
	bytesConnection         = []byte(HeaderConnection)
	bytesContentLength      = []byte(HeaderContentLength)
	bytesContentType        = []byte(HeaderContentType)
	bytesDate               = []byte(HeaderDate)
	bytesHost               = []byte(HeaderHost)
	bytesReferer            = []byte(HeaderReferer)
	bytesTransferEncoding   = []byte(HeaderTransferEncoding)
	bytesContentEncoding    = []byte(HeaderContentEncoding)
	bytesAcceptEncoding     = []byte(HeaderAcceptEncoding)
	bytesUserAgent          = []byte(HeaderUserAgent)
	bytesCookie             = []byte(HeaderCookie)
	bytesSetCookie          = []byte(HeaderSetCookie)
	bytesLocation           = []byte(HeaderLocation)
	bytesIfModifiedSince    = []byte(HeaderIfModifiedSince)
	bytesLastModified       = []byte(HeaderLastModified)
	bytesAcceptRanges       = []byte(HeaderAcceptRanges)
	bytesRange              = []byte(HeaderRange)
	bytesContentRange       = []byte(HeaderContentRange)
	bytesAuthorization      = []byte(HeaderAuthorization)
	bytesTE                 = []byte(HeaderTE)
	bytesTrailer            = []byte(HeaderTrailer)
	bytesMaxForwards        = []byte(HeaderMaxForwards)
	bytesProxyConnection    = []byte(HeaderProxyConnection)
	bytesProxyAuthenticate  = []byte(HeaderProxyAuthenticate)
	bytesProxyAuthorization = []byte(HeaderProxyAuthorization)
	bytesWWWAuthenticate    = []byte(HeaderWWWAuthenticate)
	bytesVary               = []byte(HeaderVary)

	bytesClose               = []byte("close")
	bytesGzip                = []byte("gzip")
	bytesBr                  = []byte("br")
	bytesZstd                = []byte("zstd")
	bytesDeflate             = []byte("deflate")
	bytesKeepAlive           = []byte("keep-alive")
	bytesUpgrade             = []byte("Upgrade")
	bytesChunked             = []byte("chunked")
	bytesIdentity            = []byte("identity")
	bytes100Continue         = []byte("100-continue")
	bytesPostArgsContentType = []byte("application/x-www-form-urlencoded")
	bytesDefaultContentType  = []byte("application/octet-stream")
	bytesMultipartFormData   = []byte("multipart/form-data")
	bytesBoundary            = []byte("boundary")
	bytesBytes               = []byte("bytes")
	bytesBasicSpace          = []byte("Basic ")

	bytesApplicationSlash = []byte("application/")
	bytesImageSVG         = []byte("image/svg")
	bytesImageIcon        = []byte("image/x-icon")
	bytesFontSlash        = []byte("font/")
	bytesMultipartSlash   = []byte("multipart/")
	bytesTextSlash        = []byte("text/")
)
